sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

install:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - composer validate
  - composer install

script:
  # Static analyzer check
  - if [ $TRAVIS_PHP_VERSION = '7.1' ]; then composer require "phpstan/phpstan:^0.9" && ./vendor/bin/phpstan analyze -c .phpstan.neon --level=4 --no-progress src;fi
  # Check the code style
  - if [ $TRAVIS_PHP_VERSION = '7.1' ]; then IFS=$'\n'; COMMIT_SCA_FILES=($(git diff --name-only --diff-filter=ACMRTUXB "${TRAVIS_COMMIT_RANGE}")); unset IFS; fi
  - if [ $TRAVIS_PHP_VERSION = '7.1' ]; then composer require "friendsofphp/php-cs-fixer:^2.8" && ./vendor/bin/php-cs-fixer fix --config=.php_cs.php -v --dry-run --stop-on-violation --using-cache=no --path-mode=intersection -- "${COMMIT_SCA_FILES[@]}";fi
  # Unit test
  - ./vendor/bin/phpunit
  # Integration test
  - mkdir web && echo "Hello" > web/index.html
  - bin/ppm start --workers=1 --bridge=StaticBridge --static-directory=web --max-requests=1 -v &
  - sleep 5
  - bin/ppm status
  - curl -v -f "http://127.0.0.1:8080"
  - bin/ppm status
  - curl -v -f "http://127.0.0.1:8080"
  - bin/ppm status
  - bin/ppm stop

matrix:
  fast_finish: true

# Cache package sources
cache:
  directories:
    - $HOME/.composer/cache
